services:
  opensrm:
    image: ghcr.io/thenabbu/opensrm:latest
    container_name: opensrm
    restart: unless-stopped
    ports:
      - "8083:8080"
    volumes:
      - opensrm-data:/app/data
    environment:
      - TZ=Asia/Kolkata

volumes:
  opensrm-data:
